const POT=36520,PAY={champ:POT*.36,runner:POT*.15,semi:POT*.08,qf:POT*.0425,r1:POT*.03};
const money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n||0);
const share=(t,o)=>{const i=t.owners.indexOf(o);return i<0?0:(t.shares?t.shares[i]:1/t.owners.length)};
const percent=n=>(n*100).toFixed(Number.isInteger(n*100)?0:1)+"%";
const ownership=t=>t.owners.map(o=>o+" "+percent(share(t,o))).join(" / ");
function fullEV(t,p=t.prob){if(t.team==="The Field")return POT*(p/100)*.11;const s=t.rank?Math.max(.28,1-(t.rank-1)/32):(t.votes>=40?.34:.26),b=p/100,q=b*(.48+.20*s),sf=q*(.34+.20*s),f=sf*(.33+.18*s),c=f*(.37+.18*s);return Math.max(0,b-q)*PAY.r1+Math.max(0,q-sf)*PAY.qf+Math.max(0,sf-f)*PAY.semi+Math.max(0,f-c)*PAY.runner+c*PAY.champ}
const ownerCost=o=>TEAMS.reduce((s,t)=>s+t.bid*share(t,o),0);
const ownerEV=o=>TEAMS.reduce((s,t)=>s+fullEV(t)*share(t,o),0);
const ownerAnyCash=o=>100*(1-TEAMS.filter(t=>t.owners.includes(o)).reduce((p,t)=>p*(1-t.prob/100),1));
const ownerTeams=o=>TEAMS.filter(t=>t.owners.includes(o)).map(t=>t.team);
const displayDate=d=>new Date(d+"T12:00:00").toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"});
const priorLeaderboardSnapshot=()=>[...LEADERBOARD_SNAPSHOTS].filter(s=>s.week<CURRENT_REFRESH_WEEK).sort((a,b)=>b.week.localeCompare(a.week))[0]||null;
function movementBadge(delta,hasPrior){if(!hasPrior)return '<span class="movement same" title="Baseline week">— Baseline</span>';if(delta>0)return '<span class="movement up" title="Moved up '+delta+' place'+(delta===1?'':'s')+'">▲ '+delta+'</span>';if(delta<0)return '<span class="movement down" title="Moved down '+Math.abs(delta)+' place'+(delta===-1?'':'s')+'">▼ '+Math.abs(delta)+'</span>';return '<span class="movement same" title="No change in rank">● Same</span>'}
const initials=n=>n.replace(/[^A-Za-z0-9 ]/g,"").split(" ").map(x=>x[0]).join("").slice(0,3).toUpperCase();
const dots=n=>'<div class="sched" title="Schedule difficulty '+n+'/5">'+[1,2,3,4,5].map(i=>'<span class="dot '+(i<=n?"on":"")+'"></span>').join("")+"</div>";
function card(t){const pos=Math.max(2,Math.min(98,t.prob)),rank=t.rank?"#"+t.rank:(t.votes?("RV ("+t.votes+" votes)"):"Unranked"),probLabel=t.team==="The Field"?"FPI-derived field chance":"ESPN FPI playoff chance";return '<article class="team-card metric"><div class="team-head"><div class="badge"><img src="'+t.logo+'" alt="'+t.team+' logo"></div><div><div class="team-title">'+t.team+'</div><div class="rank">'+rank+" • "+t.record+" • "+t.conference+' • Conf record '+t.conf+'</div><div class="owners">Owner'+(t.owners.length>1?"s":"")+": <b>"+ownership(t)+'</b></div></div></div><div class="result">'+t.latest+'</div><div class="prob-row"><span>'+probLabel+'</span><b>'+t.prob.toFixed(1)+'%</b></div><div class="track"><div class="fill" style="width:'+pos+'%"></div><div class="football" style="left:'+pos+'%">🏈</div></div>'+dots(t.schedule)+'<div class="prob-row"><span>Full-lot Model EV</span><b>'+money(fullEV(t))+'</b></div><div class="news">'+t.news+"</div></article>"}
const ownerFilter=document.getElementById("ownerFilter"),teamSearch=document.getElementById("teamSearch"),sortBy=document.getElementById("sortBy"),resetBtn=document.getElementById("resetBtn");
const simTeam=document.getElementById("simTeam"),simWins=document.getElementById("simWins"),simLosses=document.getElementById("simLosses"),simConfWins=document.getElementById("simConfWins"),simConfLosses=document.getElementById("simConfLosses"),simSched=document.getElementById("simSched"),simProb=document.getElementById("simProb"),simEV=document.getElementById("simEV"),simDelta=document.getElementById("simDelta"),simOwners=document.getElementById("simOwners");
ownerFilter.innerHTML=["League View",...OWNER_LIST].map(o=>"<option>"+o+"</option>").join("");
const currentOwner=()=>ownerFilter.value;
function renderSummary(){const o=currentOwner(),e=document.getElementById("portfolioSummary"),mb=document.getElementById("mobileOwnerBanner");mb.textContent=o==="League View"?"League View: showing all 36 lots and all owners.":"Viewing "+o+"'s portfolio only. Change the Portfolio filter above to switch owners.";if(o==="League View"){e.innerHTML='<div class="metric"><span class="muted">League invested</span><b>'+money(TEAMS.reduce((s,t)=>s+t.bid,0))+'</b></div><div class="metric"><span class="muted">Ranked lots</span><b>'+TEAMS.filter(t=>t.rank).length+'</b></div><div class="metric"><span class="muted">Undefeated lots</span><b>'+TEAMS.filter(t=>/^3-0$|^4-0$/.test(t.record)).length+'</b></div><div class="metric"><span class="muted">View</span><b>All owners</b></div>';return}const ts=TEAMS.filter(t=>t.owners.includes(o)),c=ownerCost(o),v=ownerEV(o);e.innerHTML='<div class="metric"><span class="muted">'+o+"'s teams</span><b>"+ts.length+'</b></div><div class="metric"><span class="muted">Invested</span><b>'+money(c)+'</b></div><div class="metric"><span class="muted">Modeled payout EV</span><b>'+money(v)+'</b></div><div class="metric"><span class="muted">EV vs cost</span><b class="'+(v>=c?"positive":"negative")+'">'+money(v-c)+'</b></div><div class="metric"><span class="muted">Any CFP cash</span><b>'+ownerAnyCash(o).toFixed(0)+"%</b></div>"}
function renderTeams(){const o=currentOwner(),q=teamSearch.value.toLowerCase(),s=sortBy.value;let r=TEAMS.filter(t=>(o==="League View"||t.owners.includes(o))&&t.team.toLowerCase().includes(q));r=[...r].sort((a,b)=>s==="prob"?b.prob-a.prob:s==="rank"?(a.rank||99)-(b.rank||99):s==="bid"?b.bid-a.bid:a.team.localeCompare(b.team));document.getElementById("teamGrid").innerHTML=r.map(card).join("")}
function renderLeaders(){const prior=priorLeaderboardSnapshot(),priorRanks=new Map((prior?.participants||[]).map(x=>[x.owner,x.rank]));const r=OWNER_LIST.map(o=>({o,c:ownerCost(o),v:ownerEV(o),p:ownerAnyCash(o),teams:ownerTeams(o)})).sort((a,b)=>b.v-a.v).map((x,i)=>({...x,rank:i+1,movement:priorRanks.has(x.o)?priorRanks.get(x.o)-(i+1):0}));document.getElementById("leaderboardAsOf").textContent="Updated "+displayDate(CURRENT_REFRESH_WEEK)+(prior?" • Movement vs. "+displayDate(prior.week):" • Baseline snapshot");document.getElementById("leaderRows").innerHTML=r.map(x=>'<tr><td class="num rank-cell"><b>'+x.rank+'</b></td><td><b>'+x.o+'</b></td><td>'+movementBadge(x.movement,priorRanks.has(x.o))+'</td><td><div class="team-chips">'+x.teams.map(t=>'<span>'+t+'</span>').join("")+'</div></td><td class="num">'+money(x.c)+'</td><td class="num"><b>'+money(x.v)+'</b></td><td class="num '+(x.v>=x.c?"positive":"negative")+'">'+money(x.v-x.c)+'</td><td class="num">'+x.p.toFixed(0)+"%</td></tr>").join("");document.getElementById("ownerMobileCards").innerHTML=r.map(x=>'<div class="owner-mobile-card"><div class="top"><div><span class="mobile-rank">#'+x.rank+'</span> <b>'+x.o+'</b></div>'+movementBadge(x.movement,priorRanks.has(x.o))+'</div><div class="mobile-team-list">'+x.teams.join(" • ")+'</div><div class="stats"><div class="stat"><span>Total invested</span><b>'+money(x.c)+'</b></div><div class="stat"><span>Modeled payout EV</span><b>'+money(x.v)+'</b></div><div class="stat"><span>EV vs cost</span><b class="'+(x.v>=x.c?"positive":"negative")+'">'+money(x.v-x.c)+'</b></div><div class="stat"><span>At least one CFP payout</span><b>'+x.p.toFixed(0)+"%</b></div></div></div>").join("")}
function simProbability(t){if(t.team==="The Field")return t.prob;const fw=+simWins.value||0,fl=+simLosses.value||0,cw=+simConfWins.value||0,cl=+simConfLosses.value||0,sd=+simSched.value||3;let p=t.prob+fw*5.2-fl*12+cw*2.6-cl*5.5-(sd-t.schedule)*1.8;if(t.rank&&t.rank<=8)p+=fw*.8;if(t.team==="Boise State")p+=Math.max(0,cw-cl)*1.6;return Math.max(.5,Math.min(98,p))}
function renderSim(){const t=TEAMS.find(x=>x.team===simTeam.value);simSched.value=t.schedule;updateSim()}
function updateSim(){const t=TEAMS.find(x=>x.team===simTeam.value),p=simProbability(t),v=fullEV(t,p),d=v-fullEV(t);simProb.textContent=p.toFixed(1)+"%";simEV.textContent=money(v);simDelta.textContent=(d>=0?"+":"")+money(d);simDelta.className="sim-out "+(d>=0?"positive":"negative");simOwners.innerHTML="Owner-adjusted scenario EV: <b>"+t.owners.map(o=>o+" "+percent(share(t,o))+" "+money(v*share(t,o))).join(" • ")+"</b>"}
simTeam.innerHTML=TEAMS.map(t=>"<option>"+t.team+"</option>").join("");
[ownerFilter,sortBy].forEach(el=>el.addEventListener("change",()=>{renderSummary();renderTeams()}));teamSearch.addEventListener("input",renderTeams);resetBtn.addEventListener("click",()=>{ownerFilter.value="League View";teamSearch.value="";sortBy.value="prob";renderSummary();renderTeams()});simTeam.addEventListener("change",renderSim);[simWins,simLosses,simConfWins,simConfLosses,simSched].forEach(el=>el.addEventListener("input",updateSim));
document.getElementById("dataThrough").textContent=displayDate(DATA_THROUGH).replace(", 2026","");renderSummary();renderTeams();renderLeaders();renderSim();
